check if valid semver successor

diff --git a/.github/workflows/create_relase_branch.yml b/.github/workflows/create_relase_branch.yml
--- a/.github/workflows/create_relase_branch.yml
+++ b/.github/workflows/create_relase_branch.yml
@@ -15,9 +15,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
-          # Ensure all branches are fetched
           fetch-tags: true
-          # Checkout the develop branch
           ref: develop
 
       - name: Set up Git
@@ -33,15 +31,44 @@ jobs:
             exit 1
           fi
 
+      - name: Fetch latest tags from master branch
+        run: |
+          git fetch origin master --tags
+          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
+          echo "Latest tag on master: $LATEST_TAG"
+        id: fetch_latest_tag
+
+      - name: Extract the version number from the latest tag
+        run: |
+          LATEST_VERSION=${{ steps.fetch_latest_tag.outputs.LATEST_TAG#v }}
+          echo "Latest version: $LATEST_VERSION"
+        id: extract_version
+
+      - name: Validate version is a valid successor
+        run: |
+          # Remove 'v' from the provided version number
+          NEW_VERSION=${{ github.event.inputs.release_version#v }}
+
+          # Ensure semver is installed
+          sudo apt-get install -y npm
+          npm install -g semver
+
+          # Compare the new version with the latest version
+          if ! npx semver $NEW_VERSION -r ">$LATEST_VERSION"; then
+            echo "Error: Provided version ($NEW_VERSION) is not a valid successor to the latest version ($LATEST_VERSION)."
+            exit 1
+          else
+            echo "Version $NEW_VERSION is a valid successor to $LATEST_VERSION."
+          fi
+        env:
+          LATEST_VERSION: ${{ steps.extract_version.outputs.LATEST_VERSION }}
+
       - name: Check for Existing Release Branches
         run: |
-          # Fetch remote branches
           git fetch origin
 
-          # Check if any remote branch starts with 'release-'
           if git ls-remote --heads origin 'release-*' | grep 'refs/heads/release-'; then
             echo "Error: An existing release branch was found. Only one release branch is allowed at a time."
-            echo "Please finish or close the existing release branch before creating a new one."
             exit 1
           else
             echo "No existing release branches found. Proceeding..."
